# Url to access prometheus
prometheus:
  url: http://prometheus-operated.default.svc.cluster.local
  port: 9090

metricsRelistInterval: 30s
logLevel: 6
rules:
  default: false
  custom:
  - seriesQuery: 'http_requests_in_progress{container="tailwindtraders-products"}'
    resources:
      overrides:
        namespace: {resource: "namespace"}
        pod: {resource: "pod"}
    name:
     as: "http_requests_in_progress"
#    metricsQuery: 'round(sum(avg_over_time(<<.Series>>{<<.LabelMatchers>>}[30s])))'
    metricsQuery: 'http_requests_in_progress'
